# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbbe88e1f4f3b6dc8b716715f41e3ed0604329737a2b46633fcdd6e07874a49a1682f8651479fbc3e304e8fe89d5b675ec7790c9d8cd1daf454554fa4dea0a03

test:
  secret_key_base: 144288c4a0fe92b568996a332994d65fcd5785a7fc59297f4db2a4c7d0f2a17c958af8d226d7ac2e548dc933ccded8e7a05e267895db25eac74a319d264272f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
